webClient:
    defaultProperties:
        connectionTimeout: 6000
        readTimeout: 6000
        writeTimeout: 9000
        maxIdleTime: 10s
        maxRetry: 2
        retryDelay: 1s
    services:
        google:
            url: http://localhost:30001
            maxRetry: 0
        github:
            url: http://localhost:30002
